// Generated by IcedCoffeeScript 1.7.1-a
(function() {
  var App, AttributesForm, B, ExamplesHeading, ExamplesRow, ExamplesTable, LinkedState, R, RC, RulesList, button, caption, div, form, input, label, li, manualRelation, p, table, td, th, tr, ul, _ref;

  B = Backbone;

  R = React;

  RC = R.createClass;

  LinkedState = R.addons.LinkedStateMixin;

  _ref = R.DOM, div = _ref.div, ul = _ref.ul, li = _ref.li, p = _ref.p, table = _ref.table, caption = _ref.caption, tr = _ref.tr, th = _ref.th, td = _ref.td, form = _ref.form, label = _ref.label, input = _ref.input, button = _ref.button;

  AttributesForm = RC({
    render: function() {
      return form({
        onSubmit: this.explore
      }, [
        label({}, 'Перечислите свойства через "|": '), input({
          valueLink: this.props.attributesValueLink,
          style: {
            width: '50%'
          },
          autoFocus: true
        }), button({}, 'Исследовать')
      ]);
    },
    explore: function() {
      this.props.onExplore();
      return false;
    }
  });

  ExamplesHeading = RC({
    render: function() {
      var cells;
      cells = this.props.attributes.map(function(attr) {
        return th({}, attr);
      });
      return tr({}, th({}, ' '), cells);
    }
  });

  ExamplesRow = RC({
    render: function() {
      var cells;
      cells = this.props.values.map(function(val) {
        return td({}, val);
      });
      return tr({}, cells);
    }
  });

  ExamplesTable = RC({
    render: function() {
      var rows;
      rows = this.props.examples.map(function(example) {
        return ExamplesRow({
          values: example
        });
      });
      return table({}, [
        caption({}, 'Примеры'), ExamplesHeading({
          attributes: this.props.attributes
        }), rows
      ]);
    }
  });

  RulesList = RC({
    render: function() {
      var items;
      items = this.props.rules.map(function(_arg) {
        var from, to;
        from = _arg[0], to = _arg[1];
        return li({}, from.length ? "Если " + from + ", то " + to : "Всегда " + to);
      });
      return div({}, [p({}, 'Правила'), ul({}, items)]);
    }
  });

  manualRelation = function() {
    var cache;
    cache = {};
    return function(g1, m1) {
      var rel;
      cache[g1] = cache[g1] || {};
      rel = cache[g1][m1];
      if (rel != null) {
        return rel;
      } else {
        return cache[g1][m1] = confirm("" + g1 + " — " + m1 + "?");
      }
    };
  };

  App = RC({
    mixins: [LinkedState],
    render: function() {
      return div({}, [
        AttributesForm({
          attributesValueLink: this.linkState('attributes'),
          onExplore: this.explore
        }), ExamplesTable({
          attributes: this.attributes(),
          examples: this.state.examples
        }), RulesList({
          rules: this.state.rules
        })
      ]);
    },
    getInitialState: function() {
      return {
        attributes: '',
        examples: [],
        rules: [],
        model: {
          examples: [],
          rules: []
        }
      };
    },
    attributes: function() {
      return _.chain(this.state.attributes.split('|')).map(function(s) {
        return s.trim();
      }).without('').value();
    },
    explore: function() {
      var relation;
      relation = manualRelation();
      fca.off('add-example');
      fca.on('add-example', (function(_this) {
        return function(g1) {
          _this.state.model.examples.push([g1].concat(_this.attributes().map(function(m1) {
            if (relation(g1, m1)) {
              return '✓';
            } else {
              return '';
            }
          })));
          return _this.setState(_this.state.model);
        };
      })(this));
      fca.off('add-rule');
      fca.on('add-rule', (function(_this) {
        return function(from, to) {
          _this.state.model.rules.push([from, to]);
          return _this.setState(_this.state.model);
        };
      })(this));
      this.state.model.examples = [];
      this.state.model.rules = [];
      this.setState(this.state.model);
      return fca.explore([], this.attributes(), relation, {
        confirmationMessage: function(from, to) {
          if (from.length) {
            return "Если " + from + ", то " + to + "?";
          } else {
            return "Всегда ли " + to + "?";
          }
        },
        counterexampleMessage: 'Контрпример:'
      });
    }
  });

  R.renderComponent(App(), document.body);

}).call(this);
