// Generated by CoffeeScript 1.6.3
(function() {
  var m, relation;

  relation = function(g1, m1) {
    return {
      even: function(x) {
        return x % 2 === 0;
      },
      odd: function(x) {
        return x % 2 === 1;
      },
      prime: function(x) {
        var i, _i, _ref;
        switch (false) {
          case !(x < 2):
            return false;
          case !(x < 4):
            return true;
          case x % 2 !== 0:
            return false;
          case !(x < 9):
            return true;
          default:
            for (i = _i = 5, _ref = Math.floor(Math.sqrt(x)); _i <= _ref; i = _i += 6) {
              if (x % i === 0 || x % (i + 2) === 0) {
                return false;
              }
            }
            return true;
        }
      }
    }[m1](g1);
  };

  m = ["even", "odd", "prime"];

  fca.on('add-rule', function(from, to) {
    return document.write("New rule: " + from + " → " + to + "\n");
  });

  fca.on('add-example', function(e1) {
    return document.write("New example: " + e1 + "\n");
  });

  fca.explore([], m, relation, {
    parse: parseInt
  });

}).call(this);
